<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="Views\Student\SelectUnits.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Views\Student\SelectUnits.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MelliMaharat.Infrastructure\MelliMaharat.Infrastructure.csproj" />
  </ItemGroup>

</Project>
