global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using MelliMaharat.Models.Base;
global using MelliMaharat.Models.Owned;
global using System.ComponentModel.DataAnnotations.Schema;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using MelliMaharat.Models.Configurations;
global using MelliMaharat.Models.Views;
global using MelliMaharat.Models.Interfaces;